service: cleanup

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  region: us-east-1
  memorySize: 256
  timeout: 15
  deploymentBucket: sls-depl-${self:provider.region}-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:BatchWriteItem
      Resource:
        - { "Fn::Join" : [ ":", [ "arn:aws:dynamodb:${self:provider.region}", { "Ref" : "AWS::AccountId" }, "table/${self:custom.userTable}" ] ] }
        - { "Fn::Join" : [ ":", [ "arn:aws:dynamodb:${self:provider.region}", { "Ref" : "AWS::AccountId" }, "table/${self:custom.accessTokenTable}" ] ] }
        - { "Fn::Join" : [ ":", [ "arn:aws:dynamodb:${self:provider.region}", { "Ref" : "AWS::AccountId" }, "table/${self:custom.sampleTokenTable}" ] ] }
    - Effect: Allow
      Action:
        - dynamodb:BatchWriteItem
        - dynamodb:Query
      Resource:
        - { "Fn::Join" : [ ":", [ "arn:aws:dynamodb:${self:provider.region}", { "Ref" : "AWS::AccountId" }, "table/${self:custom.sampleTable}" ] ] }
  environment:
    ACCESS_TOKEN_TABLE: ${self:custom.accessTokenTable}
    SAMPLE_TABLE: ${self:custom.sampleTable}
    SAMPLE_TOKEN_TABLE: ${self:custom.sampleTokenTable}
    USER_TABLE: ${self:custom.userTable}

functions:
  cleanup:
    handler: index.cleanup
    events:
      - sns:
          topicName: ${self:custom.cleanupTopic}
          displayName: Account cleanup pipeline

#
# Custom section
#
custom:
  defaultStage: dev
  profiles:
    dev: development
    prod: production
  postfixes:
    dev: "-dev"
    prod: "-prod"
  common: ${file(../conf/common.json)}
  config: ${file(../conf/config-${self:provider.stage}.json)}
  postfix: ${self:custom.postfixes.${self:provider.stage}}
  accessTokenTable: ${self:custom.common.accessTokenTable}${self:custom.postfix}
  cleanupTopic: ${self:custom.common.cleanupTopic}${self:custom.postfix}
  sampleTable: ${self:custom.common.sampleTable}${self:custom.postfix}
  sampleTokenTable: ${self:custom.common.sampleTokenTable}${self:custom.postfix}
  userTable: ${self:custom.common.userTable}${self:custom.postfix}
