service: isp-check-sls

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.defaultStage}
  region: us-east-1
  memorySize: 128
  timeout: 15
  deploymentBucket: sls-depl-${self:provider.region}-${self:provider.stage}

functions:
  hello:
    handler: index.handler
    events:
      - http:
          path: sample
          cors: true
          method: post
          authorizer:

custom:
  defaultStage: dev
  profiles:
    dev: development
    prod: production
  common: ${file(./common.json)}
